/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AssignRouteImport } from './routes/assign'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendEmailsRouteImport } from './routes/api/send-emails'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignRoute = AssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailsRoute = ApiSendEmailsRouteImport.update({
  id: '/api/send-emails',
  path: '/api/send-emails',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assign': typeof AssignRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/api/send-emails': typeof ApiSendEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assign': typeof AssignRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/api/send-emails': typeof ApiSendEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assign': typeof AssignRoute
  '/results': typeof ResultsRoute
  '/support': typeof SupportRoute
  '/api/send-emails': typeof ApiSendEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assign' | '/results' | '/support' | '/api/send-emails'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assign' | '/results' | '/support' | '/api/send-emails'
  id:
    | '__root__'
    | '/'
    | '/assign'
    | '/results'
    | '/support'
    | '/api/send-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignRoute: typeof AssignRoute
  ResultsRoute: typeof ResultsRoute
  SupportRoute: typeof SupportRoute
  ApiSendEmailsRoute: typeof ApiSendEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign': {
      id: '/assign'
      path: '/assign'
      fullPath: '/assign'
      preLoaderRoute: typeof AssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-emails': {
      id: '/api/send-emails'
      path: '/api/send-emails'
      fullPath: '/api/send-emails'
      preLoaderRoute: typeof ApiSendEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignRoute: AssignRoute,
  ResultsRoute: ResultsRoute,
  SupportRoute: SupportRoute,
  ApiSendEmailsRoute: ApiSendEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
